title: Maxim Gutjahr
description: Latest Announcements

author:
  name: Maxim Gutjahr
  email: "contact@maximgutjahr.com"

social-network-links:
  twitter: maxim_gtjhr
  youtube: c/MaximGutjahr
  spotify: GRAVEYARDGOD
  discord: users/824294179210526801
  
date_format: "%B %d, %Y"

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto