title: Maxim Gutjahr
description: Latest Announcements

author:
  name: Maxim Gutjahr
  email: "contact@maximgutjahr.com"

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%B %d, %Y"
