title: Maxim Gutjahr
description: Latest Announcements

author:
  name: Maxim Gutjahr
  email: "contact@maximgutjahr.com"

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%B %d, %Y"

  social_links:
    - platform: twitter
      user_url: "https://twitter.com/maxim_gtjhr"
    - platform: instagram
      user_url: "https://github.com/jekyll/jekyll"
    - platform: youtube
      user_url: "https://www.youtube.com/channel/UCUTZjJieqc4e80GR0xuct6A"